server:
  port: 8081

logging:
  level:
    root: info

spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC"
    username: "root"
    password: "!Password404!"
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true

####### resource server configuration properties
  security:
    oauth2:

      resourceserver:
        jwt:
          issuer-uri: "${keycloak.base.URL}/realms/${keycloak.base.realm}"

      client:
        registration:
          keycloak:
            client-id: user-rs
            client-secret: pvPxOeuMoW2eJraXIFzqP8A8sMSs8KFw
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: openid
        provider:
          keycloak:
            token-uri: "${keycloak.base.URL}/realms/${keycloak.base.realm}/protocol/openid-connect/token"

keycloak:
  base:
    URL: "http://localhost:8080"
    realm: "oauth2-realm"
  webclient:
    registrationId: "keycloak"
    url: "${keycloak.base.URL}/admin/realms/${keycloak.base.realm}"